from tkinter import *
import matplotlib.pyplot as plt
gui = Tk()
gui.title('Balance sheet and Net income')
var = IntVar()
def openwindow():
    Info = Tk()
    Info.title('Balance sheet information')
    Info.geometry('800x500')
    Info.configure(background='white')

    def sum():
       a=int(l1.get()) 
       b=int(e1.get())
       c=a+b
       a1.insert(0,c)
       d=int(l2.get())
       e=int(e2.get())
       f=d+e
       a2.insert(0,f)
       g=int(l3.get())
       h=int(e3.get())
       i=g+h
       a3.insert(0,i)
       j=int(l4.get())
       k=int(e4.get())
       l=j+k
       a4.insert(0,l)
       m=int(l5.get())
       n=int(e5.get())
       i=m+n
       a5.insert(0,i)

    Label(Info,text='1',font=10,bg='white',fg='white').grid(row=1,column=1)
    Label(Info,text='Year 1',font=10,bg='white',fg='black').grid(row=2,column=2)
    Label(Info,text='Input information',font=10,bg='white',fg='black').grid(row=1,column=5)
    Label(Info,text='year: ',font=10,bg='white',fg='black').grid(row=3,column=3)
    y1=Entry(Info)
    y1.grid(row=3,column=4)
    Label(Info,text='liabilities: ',font=10,bg='white',fg='black').grid(row=4,column=3)
    l1=Entry(Info)
    l1.grid(row=4,column=4)
    Label(Info,text='equity:  ',font=10,bg='white',fg='black').grid(row=5,column=3)
    e1=Entry(Info)
    e1.grid(row=5,column=4)
    Label(Info,text='assests: ',font=10,bg='white',fg='black').grid(row=6, column=3)
    a1=Entry(Info)
    a1.grid(row=6,column=4)

    Label(Info,text='Year 2',font=10,bg='white',fg='black').grid(row=7,column=2)
    Label(Info,text='year:',font=10,bg='white',fg='black').grid(row=8,column=3)
    y2=Entry(Info)
    y2.grid(row=8,column=4)
    Label(Info,text='liabilities: ',font=10,bg='white',fg='black').grid(row=9,column=3)
    l2=Entry(Info)
    l2.grid(row=9,column=4)
    Label(Info,text='equity:  ',font=10,bg='white',fg='black').grid(row=10,column=3)
    e2=Entry(Info)
    e2.grid(row=10,column=4)
    Label(Info,text='assests: ',font=10,bg='white',fg='black').grid(row=11, column=3)
    a2=Entry(Info)
    a2.grid(row=11,column=4)

    Label(Info,text='Year 3',font=10,bg='white',fg='black').grid(row=12,column=2)
    Label(Info,text='year:',font=10,bg='white',fg='black').grid(row=13,column=3)
    y3=Entry(Info)
    y3.grid(row=13,column=4)
    Label(Info,text='liabilities: ',font=10,bg='white',fg='black').grid(row=14,column=3)
    l3=Entry(Info)
    l3.grid(row=14,column=4)
    Label(Info,text='equity:  ',font=10,bg='white',fg='black').grid(row=15,column=3)
    e3=Entry(Info)
    e3.grid(row=15,column=4)
    Label(Info,text='assests: ',font=10,bg='white',fg='black').grid(row=16, column=3)
    a3=Entry(Info)
    a3.grid(row=16,column=4)

    Label(Info,text='Year 4',font=10,bg='white',fg='black').grid(row=2,column=6)
    Label(Info,text='year:',font=10,bg='white',fg='black').grid(row=3,column=7)
    y4=Entry(Info)
    y4.grid(row=3,column=8)
    Label(Info,text='liabilities: ',font=10,bg='white',fg='black').grid(row=4,column=7)
    l4=Entry(Info)
    l4.grid(row=4,column=8)
    Label(Info,text='equity:  ',font=10,bg='white',fg='black').grid(row=5,column=7)
    e4=Entry(Info)
    e4.grid(row=5,column=8)
    Label(Info,text='assests: ',font=10,bg='white',fg='black').grid(row=6, column=7)
    a4=Entry(Info)
    a4.grid(row=6,column=8)

    Label(Info,text='Year 5',font=10,bg='white',fg='black').grid(row=7,column=6)
    Label(Info,text='year:',font=10,bg='white',fg='black').grid(row=8,column=7)
    y5=Entry(Info)
    y5.grid(row=8,column=8)
    Label(Info,text='liabilities: ',font=10,bg='white',fg='black').grid(row=9,column=7)
    l5=Entry(Info)
    l5.grid(row=9,column=8)
    Label(Info,text='equity:  ',font=10,bg='white',fg='black').grid(row=10,column=7)
    e5=Entry(Info)
    e5.grid(row=10,column=8)
    Label(Info,text='assests: ',font=10,bg='white',fg='black').grid(row=11, column=7)
    a5=Entry(Info)
    a5.grid(row=11,column=8)
    Button(Info,text='click for show your assest',fg='black',bg='white',command=sum).grid(row=13,column=8)

    def opg():
        x=[a1.get(),a2.get(),a3.get(),a4.get(),a5.get()]
        y=[y1.get(),y2.get(),y3.get(),y4.get(),y5.get()]
        plt.bar(y,x)
        plt.title('balance sheet')
        plt.ylabel('asset')
        plt.xlabel('years')
        plt.show()
    Button(Info, text="Next to show your graph", fg='black', bg='white',command=opg).grid(row=20,column=8)
    Info.mainloop()

def ow2():#net income
    NI = Tk()
    NI.title('Comprehensive income information')
    NI.configure(background="white")
    NI.geometry('800x500')

    def Tax():
        income=i1.get(),i2.get(),i3.get(),i4.get(),i5.get()
        if income in range(0,150000):
            tax = 0
        elif income in range(150001,300000):
            tax = income-(((income - 150000)*0.05)+0)
        elif income in range(300001,500000):
            tax = income-(((income - 300000)*0.10)+7500) 
        elif income in range(500001,750000):
            tax = income(((income - 500000)*0.15)+27500)
        elif income in range(750001,1000000):
            tax = income-(((income - 750000)*0.20)+65000)
        elif income in range(1000001,2000000):
            tax = income-(((income-1000000)*0.25)+115000) 
        elif income in range(2000001,5000000):
            tax = income-(((income-2000000)*0.30)+365000)
        elif income >= 5000001:
            tax = income-(((income-5000000)*0.35)+1265000)

        b1 = int(i1.get())
        c1 = int(x1.get())
        d1 = (b1-c1)- Tax
        n1.insert(0,d1)
        b2 = int(i2.get())
        c2 = int(x2.get())
        d2 = (b2-c2)-Tax
        n2.insert(0,d2)
        b3 = int(i3.get())
        c3 = int(x3.get())
        d3 = (b3-c3)-Tax
        n3.insert(0,d3)
        b4 = int(i4.get())
        c4 = int(x4.get())
        d4 = (b4-c4)-Tax
        n4.insert(0,d4)
        b5 = int(i5.get())
        c5 = int(x5.get())
        d5 = int(b5-c5)-Tax
        n5.insert(0,d5)

    Label(NI,text='Net Income ',font=10,bg='white',fg='black').grid(row=1, column=5)
    Label(NI,text='year1 ',font=10,bg='white',fg='black').grid(row=2, column=1)
    Label(NI,text='year: ',font=10,bg='white',fg='black').grid(row=3, column=2)
    Entry(NI).grid(row=3,column=3)
    Label(NI,text='income: ',font=10,bg='white',fg='black').grid(row=4, column=2)
    i1=Entry(NI)
    i1.grid(row=4,column=3)
    Label(NI,text='expense: ',font=10,bg='white',fg='black').grid(row=5, column=2)
    x1=Entry(NI)
    x1.grid(row=5,column=3)
    Label(NI,text='net profit: ',font=10,bg='white',fg='black').grid(row=6, column=2)
    n1=Entry(NI)
    n1.grid(row=6,column=3)

    Label(NI,text='year2 ',font=10,bg='white',fg='black').grid(row=7, column=1)
    Label(NI,text='year: ',font=10,bg='white',fg='black').grid(row=8, column=2)
    Entry(NI).grid(row=8,column=3)
    Label(NI,text='income: ',font=10,bg='white',fg='black').grid(row=9, column=2)
    i2=Entry(NI)
    i2.grid(row=9,column=3)
    Label(NI,text='expense: ',font=10,bg='white',fg='black').grid(row=10, column=2)
    x2=Entry(NI)
    x2.grid(row=10,column=3)
    Label(NI,text='net profit: ',font=10,bg='white',fg='black').grid(row=11, column=2)
    n2=Entry(NI)
    n2.grid(row=11,column=3)

    Label(NI,text='year3 ',font=10,bg='white',fg='black').grid(row=12, column=1)
    Label(NI,text='year: ',font=10,bg='white',fg='black').grid(row=13, column=2)
    Entry(NI).grid(row=13,column=3)
    Label(NI,text='income: ',font=10,bg='white',fg='black').grid(row=14, column=2)
    i3=Entry(NI)
    i3.grid(row=14,column=3)
    Label(NI,text='expense: ',font=10,bg='white',fg='black').grid(row=15, column=2)
    x3=Entry(NI)
    x3.grid(row=15,column=3)
    Label(NI,text='net profit: ',font=10,bg='white',fg='black').grid(row=16, column=2)
    n3=Entry(NI)
    n3.grid(row=16,column=3)

    Label(NI,text='year4 ',font=10,bg='white',fg='black').grid(row=2, column=6)
    Label(NI,text='year: ',font=10,bg='white',fg='black').grid(row=3, column=7)
    Entry(NI).grid(row=3,column=8)
    Label(NI,text='income: ',font=10,bg='white',fg='black').grid(row=4, column=7)
    i4=Entry(NI)
    i4.grid(row=4,column=8)
    Label(NI,text='expense: ',font=10,bg='white',fg='black').grid(row=5, column=7)
    x4=Entry(NI)
    x4.grid(row=5,column=8)
    Label(NI,text='net profit: ',font=10,bg='white',fg='black').grid(row=6, column=7)
    n4=Entry(NI)
    n4.grid(row=6,column=8)

    Label(NI,text='year5 ',font=10,bg='white',fg='black').grid(row=7, column=6)
    Label(NI,text='year: ',font=10,bg='white',fg='black').grid(row=8, column=7)
    Entry(NI).grid(row=8,column=8)
    Label(NI,text='income: ',font=10,bg='white',fg='black').grid(row=9, column=7)
    i5=Entry(NI)
    i5.grid(row=9,column=8)
    Label(NI,text='expense: ',font=10,bg='white',fg='black').grid(row=10, column=7)
    x5=Entry(NI)
    x5.grid(row=10,column=8)
    Label(NI,text='net profit: ',font=10,bg='white',fg='black').grid(row=11, column=7)
    n5=Entry(NI)
    n5.grid(row=11,column=8)
    Button(NI, text='Calculate net income',font=10,fg='black', bg='white',command=Tax).grid(row=14,column=8)
    NI.mainloop()

gui.geometry('300x200')
gui.configure(background="white")
Label(gui, text='Please choose', font=20, bg='white', fg='black').pack()
R1 = Checkbutton(gui, text="Balance sheet",variable=var, onvalue=1,offvalue=0,command=openwindow, bg='white',font=10)
R1.pack( anchor = W,padx=30,pady=10)
R2 = Checkbutton(gui, text="Comprehensive income", variable=var, onvalue=0,offvalue=0,command=ow2,bg='white',font=10)
R2.pack( anchor = W, padx=30,pady=5 )
gui.mainloop()
